name: opal_me
description: "A premium project management and chat application for portfolio."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons & UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0        # لإضافة خطوط بريميوم للـ CV
  
  # Local Storage (Alternative to Firebase for CV)
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # لو عندك صور أو أيقونات ضيفها هنا تحت الـ assets
  # assets:
  #   - assets/images/